// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk51_VlLreET73408KqOmssH60p_aBnNo',
    appId: '1:86368546930:web:35938fd50b6b4e588e92eb',
    messagingSenderId: '86368546930',
    projectId: 'prof-ecommerce',
    authDomain: 'prof-ecommerce.firebaseapp.com',
    storageBucket: 'prof-ecommerce.appspot.com',
    measurementId: 'G-D1M5RRS6BY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkdi8puvgvwt9OgXYULd_SFhaJg2A2FpQ',
    appId: '1:86368546930:android:8921d5775b65b7de8e92eb',
    messagingSenderId: '86368546930',
    projectId: 'prof-ecommerce',
    storageBucket: 'prof-ecommerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTW7P7gBWRY6n6YfiKWSbWROaZCtUYXWk',
    appId: '1:86368546930:ios:fd25c14adec15d228e92eb',
    messagingSenderId: '86368546930',
    projectId: 'prof-ecommerce',
    storageBucket: 'prof-ecommerce.appspot.com',
    androidClientId: '86368546930-f0vphuio01gpo57rgaatdn653hpacmca.apps.googleusercontent.com',
    iosClientId: '86368546930-rk90f0t3mv8psfulj5uq1s9qhgue62uc.apps.googleusercontent.com',
    iosBundleId: 'com.example.profEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTW7P7gBWRY6n6YfiKWSbWROaZCtUYXWk',
    appId: '1:86368546930:ios:fd25c14adec15d228e92eb',
    messagingSenderId: '86368546930',
    projectId: 'prof-ecommerce',
    storageBucket: 'prof-ecommerce.appspot.com',
    iosBundleId: 'com.example.profEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk51_VlLreET73408KqOmssH60p_aBnNo',
    appId: '1:86368546930:web:49a5508a0d8c96808e92eb',
    messagingSenderId: '86368546930',
    projectId: 'prof-ecommerce',
    authDomain: 'prof-ecommerce.firebaseapp.com',
    storageBucket: 'prof-ecommerce.appspot.com',
    measurementId: 'G-9KK211Q5CN',
  );
}